//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telegramBod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelegramUser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
